Ext.define('Abraxa.store.common.commodity.CommodityTypes', {
    storeId: 'store-commoditytypes',
    extend: 'Ext.data.Store',
    alias: 'store.commoditytypes',
    autoLoad: true,
    fields: ['name'],
    data: [
        { name: 'bags' },
        { name: 'barrels' },
        { name: 'drums' },
        { name: 'bulk' },
        { name: 'boxes' },
        { name: 'cartons' },
        { name: 'shelled in bags' },
        { name: 'unshelled in bags' },
        { name: 'cases' },
        { name: 'mats' },
        { name: 'casks' },
        { name: 'slabs' },
        { name: 'ingots' },
        { name: 'pockets' },
        { name: 'pressed bales' },
        { name: 'pallets' },
        { name: 'bundles' },
        { name: 'bales' },
        { name: 'kegs' },
        { name: 'packs' },
        { name: 'rolls' },
        { name: 'pulp' },
        { name: 'unpacked' },
        { name: 'crates' },
        { name: 'chests' },
        { name: 'tins' },
        { name: 'briquettes' },
        { name: 'pellets' },
        { name: 'fines' },
        { name: 'loose' },
        { name: 'big bags' },
        { name: 'carcasses' },
        { name: 'packing' },
        { name: 'jars' },
        { name: 'unknown' },
    ],
    proxy: {
        type: 'memory',
    },
});
