Ext.define('Abraxa.utils.AbraxaConstants', {
    alternateClassName: ['AbraxaConstants'],
    singleton: true,
    /**
     * Define constants of labels and repeated string to avoid mistakes
     * usage: AbraxaConstants.constant
     */
    files: {
        maxFileSize: 10 * 1024 * 1024,
    },
    labels: {
        vessel: 'vessel',
        voyageNumber: 'voyage_number',
        leadAgent: 'lead_agent',
        subAgent: 'sub_agent',
        appointingParty: 'appointing_party',
        nominatingParty: 'nominating_party',
        organization: 'organization',
        organizationName: 'org_name',
        type: 'type',
        defaultExpenseItem: 'default_expense_item',
        cargoQuantity: 'cargo_quantity',
        latestEvent: 'latest_event',
        createdByUser: 'created_by_user',
    },
    titles: {
        addBerth: "Let's add a Berth",
        addPort: "Let's add a Port",
        addTerminal: "Let's add a Terminal",
        delete: 'Delete',
        editBerth: "Let's edit the Berth",
        editPort: "Let's edit the Port",
        editTerminal: "Let's edit the Terminal",
    },
    messages: {
        deleteSharedRecord: 'Are you sure you want to delete a record that is not your own?',
        deleteRecord: 'Record deleted',
        deleteItem: 'Are you sure you want to delete this item?',
        deleteDisbursement: 'Are you sure? </br>Deleting this DA would also delete any related payments.',
        updateRecord: 'Record updated',
        dateFormatError: ' date cannot be formatted.',
        createRecord: 'Record created',
        anErrorOccured: {
            title: 'An error occurred',
            message:
                'We are sorry, but we are unable to process your request right now. </br>Please contact your system support.',
        },
    },
    formatters: {
        date: {
            dayMonYear: 'd M y',
            dayMonHyphenTime24: 'd M - H:i',
            dayMonYearShortHyphenTime24: 'd M Y - H:i',
            dayMonYearTime24: 'DD MMM YY HH:mm',
            dayMonthYearTime24Slash: 'd/m/Y H:i',
            dayMonYearHyphenTime24: 'DD MMM YY - HH:mm',
            dayMonthYearSlash: 'DD/MM/YYYY',
            dayMonthYearSlashShort: 'dd/mm/yyyy',
            dayMonthYearSlashNoLeading: 'd/m/Y',
            dayAbbrMonYear: 'D MMM YY',
            dayMonHyphenTime12: 'j M - H:i',
            dayAbbrMonYearHyphenTime24: 'D MMM YY - HH:mm',
            yearMonthDayHyphen: 'Y-m-d',
        },
    },
    placeholders: {
        emptyHtmlChar: '&nbsp;',
        emptySpan: '<span class="a-placeholder">---</span>',
        emptyValue: '---',
        emptyCellSpan: '<span class="a-cell-placeholder">---</span>',
        emptyStatusDiv: '<div class="a-status-badge a-status-md">---</div>',
        emptyAmountSpan: '<span class="a-cell-placeholder">0,000.00</span>',
        emptySpanWithZeroValue: '<span class="a-cell-placeholder">0</span>',
        emptySpanWithZeroPercentage: '<span class="a-cell-placeholder">0%</span>',
        emptySpanWithDoubleZero: '<span class="a-cell-placeholder">0</span>',
        noValueWithIcon: '<span class="a-value-no"><i class="md-icon"></i> No</span>',
        yesValueWithIcon: '<span class="a-value-yes"><i class="md-icon"></i> Yes</span>',
        noValueWithoutIcon: '<span>No</span>',
        yesValueWithoutIcon: '<span>Yes</span>',
        zeroValue: '0,000.00',
    },
    urls: {
        staticAbraxa: 'https://static.abraxa.com/',
    },
    buttons: {
        text: {
            cancel: 'Cancel',
            save: 'Save',
            delete: 'Delete',
            ok: 'Ok',
            yes: 'Yes',
            no: 'No',
            pendingApproval: 'Pending approval',
            draft: 'Draft',
            submitted: 'Submitted',
            approved: 'Approved',
            completed: 'Completed',
            settled: 'Settled',
            rejected: 'Rejected',
        },
    },
});
